### ISSUE TITLE
NameError: name 'FILETYPE_PEM' is not defined

### ISSUE THREAD

**Issue by setterlee** [dansanti/user_signature_key#4]
In company_signature_key.py and user_signature_key.py Python show the follow error:

> app_1  | Traceback (most recent call last):
> app_1  |   File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
> app_1  |     execute(self.server.app)
> app_1  |   File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
> app_1  |     application_iter = app(environ, start_response)
> app_1  |   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 249, in app
> app_1  |     return self.app(e, s)
> app_1  |   File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 184, in application
> app_1  |     return application_unproxied(environ, start_response)
> app_1  |   File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 170, in application_unproxied
> app_1  |     result = handler(environ, start_response)
> app_1  |   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1496, in __call__
> app_1  |     self.load_addons()
> app_1  |   File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1517, in load_addons
> app_1  |     m = __import__('openerp.addons.' + module)
> app_1  |   File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 61, in load_module
> app_1  |     mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
> app_1  |   File "/mnt/extra-addons/user_signature_key/__init__.py", line 2, in <module>
> app_1  |     from . import models
> app_1  |   File "/mnt/extra-addons/user_signature_key/models/__init__.py", line 3, in <module>
> app_1  |     from . import company_signature_key
> app_1  |   File "/mnt/extra-addons/user_signature_key/models/company_signature_key.py", line 21, in <module>
> app_1  |     type_ = FILETYPE_PEM
> app_1  | NameError: name 'FILETYPE_PEM' is not defined

**Comment by dansanti** [comment]
Hi! you need to install the correct version of m2crypto, this installation don't accept latest version of it:

https://globalresponse.cl/blog/nuestro-blog-1/post/instalacion-facturacion-electronica-4

**Comment by setterlee** [comment]
The version installed is the 0.24.0 as the installation post suggested.

**Comment by dansanti** [comment]
try wit signxml ==1.0.1 but that is a problem with depends, please use forum for support

**Comment by setterlee** [comment]
Modifying the import sentence from “from OpenSSL.crypto import *” to “from OpenSSL import crypto” and the type_ declaration from “type_ = FILETYPE_PEM” to ”type_ = crypto.FILETYPE_PEM” works for me... because of that I think that is no a dependencies issue...
